---
#configure
- name: index.html
  copy: src=index.html dest=/var/www/html/index.html
  notify:
    - restart nginx service

- name: copy custom.html
  template:
    src: templates/custom.html.j2 dest=/var/www/html/index.html
  notify:
    - restart nginx service  
