---
#configure
- name: copy zoidberg
  copy: src=zoidberg.png dest=/var/www/html/zoidberg.png

- name: copy index.html
  template:
    src: templates/index.html.j2
    #dest: /var/www/html/index.html
  notify:
    - restart nginx service
